name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: ./lessons/4-testing-infrastructure/4.2-installing-dependencies-by-docker
        run: make composer-install

      - name: Start all the environment
        working-directory: ./lessons/4-testing-infrastructure/4.2-installing-dependencies-by-docker
        run: make start

      - name: Wait for the environment to get up
        run: |
          while ! make ping-mysql; do
              echo "Waiting for database connection..."
              sleep 2
          done

      - name: Run the tests
        working-directory: ./lessons/4-testing-infrastructure/4.2-installing-dependencies-by-docker
        run: make test