name: First workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Hello Codelies!
        run: echo "Hello!!!! from ${{ github.workflow }} triggered by the ${{ github.event_name }} done by ${{ github.actor }}"

      - name: 😊 More and more
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: |
          echo "Job Context: $JOB_CONTEXT"
          echo "Done!"

      - name: Install infra dependencies
        run: sh etc/install.sh

      - name: Install application dependencies
        working-directory: ./lessons/4-testing-infrastructure/4.1-installing-dependencies-by-hand
        run: composer install --ignore-platform-reqs

      - name: Run the tests
        working-directory: ./lessons/4-testing-infrastructure/4.1-installing-dependencies-by-hand
        run: composer phpunit